name: CI - Calculadora de Precificacao

# 1. Define QUANDO o robô vai rodar
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. Define O QUE o robô vai fazer
jobs:
  build-and-test:
    name: Build e Testes Automatizados
    runs-on: ubuntu-latest # Roda em um servidor Linux rápido e barato na nuvem

    steps:
    # Passo A: Baixa o seu código do repositório
    - name: 📥 Fazer checkout do código
      uses: actions/checkout@v4

    # Passo B: Instala o ambiente do C# (.NET) no servidor do GitHub
    - name: ⚙️ Configurar o .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Versão mais atual e estável

# Passo C: Instala as dependências
    - name: 📦 Restaurar dependências
      run: dotnet restore

    # Passo D: LINTING / Análise Estática (NOVO!)
    - name: 🔍 Análise Estática (Linting)
      run: dotnet format --verify-no-changes

    # Passo E: Compila o projeto (Build)
    - name: 🛠️ Compilar o projeto (Build)
      run: dotnet build --no-restore --configuration Release

    # Passo F: Roda os testes
    - name: 🧪 Executar Testes Automatizados
      run: dotnet test --no-build --configuration Release --verbosity normal